title: Shanief Webb
avatar: https://media.licdn.com/dms/image/v2/D4E03AQGTpeHfjO4wBw/profile-displayphoto-crop_800_800/B4EZtNo4HRIoAI-/0/1766534120390?e=1767830400&v=beta&t=bLZZ554sdueOFe2GVlHrgqMya6C-2R2ZS8fnImMyOMc
email: word-left-snowshoe@duck.com
github_username: slw07g
twitter_username: feinahs
description: >- 
  Bridging the gap between high-level security strategy and cloud infrastructure reality. This blog explores the frameworks necessary to build resilient systems, foster cross-functional collaboration, and mentor the next generation of security engineers. From incident response to enterprise security architecture, we focus on the long-term vision of a secure digital future.
baseurl: "" 
url: "https://shanief.com"

# Build settings
remote_theme: pages-themes/architect # Optional: if starting from a base
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter_opts:
    block_code_attr_class: 'highlight'
